# Generated by Django 6.0.5 on 2026-06-01 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=32)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('avatar_key', models.CharField(blank=True, default='', max_length=500)),
                ('banner_key', models.CharField(blank=True, default='', max_length=500)),
                ('status_preference', models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
