# Generated by Django 6.0.5 on 2026-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name_effect',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='frame_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
