# Generated by Django 6.0.5 on 2026-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deviceverificationcode_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_shape',
            field=models.CharField(choices=[('square', 'Square'), ('round', 'Round')], default='square', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_status_badge',
            field=models.BooleanField(default=True),
        ),
    ]
