# Generated by Django 6.0.5 on 2026-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_avatar_shape_profile_show_status_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
