# Generated by Django 6.0.5 on 2026-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
    ]
