# Generated by Django 6.0.2 on 2026-02-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_users',
            field=models.IntegerField(default=0),
        ),
    ]
